settings:
  content:
    merge: true
media: src/assets
content:
  - name: heroSection
    type: file
    label: Hero Section
    path: src/data/hero.json
    format: json
    fields:
      - name: heading
        label: Heading
        type: string
        required: true
      - name:  subheading
        label: Sub Heading
        type: string
      - name: buttonText
        label: Button Text
        type: string
  - name: communityHelp
    label: Community Help Section
    path: src/data/whatToDo.json
    type: file
    fields:
      - name: heading
        label: Heading
        type: string
        required: true
      - name: items
        label: Ways to Help
        type: object
        list: true
        fields:
          - { name: icon, label: Icon, type: string }
          - { name: title, label: Title, type: string }
  - name: communityBenefit
    label: Community Benefit Section
    path: src/data/communityBenefits.json
    type: file
    fields:
      - name: heading
        label: Heading
        type: string
        required: true
      - name: subheading
        label: Sub Heading
        type: string
      - name: items
        label: Lifelines
        type: object
        list: true
        fields:
          - { name: title, label: Title, type: string }
          - { name: description, label: Description, type: string }
  - name: businessBenefit
    label: Business Benefit Section
    path: src/data/businessBenefits.json
    type: file
    fields:
      - name: heading
        label: Heading
        type: string
        required: true
      - name: subheading
        label: Sub Heading
        type: string
      - name: items
        label: Business Benefits
        type: object
        list: true
        fields:
          - { name: title, label: Title, type: string }
          - { name: description, label: Description, type: string }
  - name: whatNext
    label: What Next Section
    path: src/data/whatNext.json
    type: file
    fields:
      - name: heading
        label: Heading
        type: string
        required: true
      - name: subheading
        label: Sub Heading
        type: string
      - name: items
        label: What Next Items
        type: object
        list: true
        fields:
          - { name: text, label: Text, type: string }
