settings:
  content:
    merge: true
media: src/assets
content:
  - name: heroSection
    type: file
    label: Hero Section
    path: src/sections/HeroSection.astro
    fields:
      - name: heading
        label: Heading
        type: text
        required: true
      - name:  subheading
        label: Sub Heading
        type: text
      - name: buttonText
        label: Button Text
        type: text
  - name: hero
    label: Hero Section
    path: src/data/hero.json
    type: file
    fields:
      - name: heading
        label: Heading
        type: text
        required: true
      - name:  subheading
        label: Sub Heading
        type: text
      - name: buttonText
        label: Button Text
        type: text
  - name: communityHelp
    label: Community Help Section
    path: src/data/whatToDo.json
    type: file
    fields:
      - name: heading
        label: Heading
        type: text
        required: true
      - name: subheading
        label: Sub Heading
        type: text
  - name: communityBenefit
    label: Community Benefit Section
    path: src/data/lifelines.json
    type: file
    fields:
      - name: heading
        label: Heading
        type: text
        required: true
      - name: subheading
        label: Sub Heading
        type: text
  - name: businessBenefit
    label: Business Benefit Section
    path: src/data/businessBenefits.json
    type: file
    fields:
      - name: heading
        label: Heading
        type: text
        required: true
      - name: subheading
        label: Sub Heading
        type: text
  - name: whatNext
    label: What Next Section
    path: src/data/whatNext.json
    type: file
    fields:
      - name: heading
        label: Heading
        type: text
        required: true
      - name: subheading
        label: Sub Heading
        type: text
